### ISSUE TITLE
增加多个事件池与回复冷却

### ISSUE THREAD

**Issue by axlmly** [TTsdzb/koishi-plugin-what-to-do#1]
未来更新考虑过增加多个事件清单池并增加可给指定的群聊分配事件池的功能吗.
例如群1能在指定的三个list里抽取事件,而群2只能在指定的两个list里抽取,群3只能在指定的一个list里抽取.
冷却部分能把今天做什么绑定给一个指令吗,这样就可以用rate-limit来限定时间和次数

**Comment by TTsdzb** [comment]
> 冷却部分能把今天做什么绑定给一个指令吗,这样就可以用rate-limit来限定时间和次数

实际上“今天做什么”还是靠触发指令实现的。因为指令的 `shortcut` 方法被弃用了，所以这里使用中间件自己模拟了一个。不知道能否被正常限制？

**Comment by TTsdzb** [comment]
如果做多个事件池的话，会让配置文件变得更加复杂，配置起来也会更麻烦，也更容易出问题。例如，可能会有人看不明白这个机制是怎么配的，只配置了事件池而没有把它分配给群，然后就出问题了……考虑到原先的设计目的是针对很少的群，这个暂时就不做了。

但是，这不代表你没法为不同的群指定不同的事件池。Koishi 现在允许一个插件有两份配置，所以你完全可以这样写：

```yaml
plugins:
  what-to-do:bzo0hi:
    list:
      - name: 事件1
  what-to-do:bzo0hd:  # 只要这个 ID 有区别就行
    list:
      - name: 事件2
```

然后 Koishi 就会把这个插件按不同的配置加载两次，你再给它们添加不同的过滤器就可以了。
